// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;
using Basic.CSV2Table;

public class StudentsAttributePlotList
{
	public class Row:BasicRow
	{
		public string PlotId;
		public string StudentID;
		public string SaveID;
		public string savePhoto;
		public string Clothing;
		public string Face;
		public string TimeBucket;
		public string CourseID;
		public string LockTime;
		public string FriendID;
		public string FriendValue;
		public string FriendMessage;

	}
	public StudentsAttributePlotList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.PlotId = grid[i][0];
			row.StudentID = grid[i][1];
			row.SaveID = grid[i][2];
			row.savePhoto = grid[i][3];
			row.Clothing = grid[i][4];
			row.Face = grid[i][5];
			row.心情 = grid[i][6];
			row.信任 = grid[i][7];
			row.气质 = grid[i][8];
			row.思维 = grid[i][9];
			row.口才 = grid[i][10];
			row.体质 = grid[i][11];
			row.善恶 = grid[i][12];
			row.语文 = grid[i][13];
			row.数学 = grid[i][14];
			row.英语 = grid[i][15];
			row.政治 = grid[i][16];
			row.历史 = grid[i][17];
			row.地理 = grid[i][18];
			row.物理 = grid[i][19];
			row.化学 = grid[i][20];
			row.生物 = grid[i][21];
			row.音乐 = grid[i][22];
			row.表演 = grid[i][23];
			row.舞蹈 = grid[i][24];
			row.手工 = grid[i][25];
			row.棋技 = grid[i][26];
			row.种植 = grid[i][27];
			row.摄影 = grid[i][28];
			row.烹饪 = grid[i][29];
			row.考古 = grid[i][30];
			row.编程 = grid[i][31];
			row.绘画 = grid[i][32];
			row.运动 = grid[i][33];
			row.TimeBucket = grid[i][34];
			row.CourseID = grid[i][35];
			row.LockTime = grid[i][36];
			row.FriendID = grid[i][37];
			row.FriendValue = grid[i][38];
			row.FriendMessage = grid[i][39];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_PlotId(string find)
	{
		return rowList.Find(x => x.PlotId == find);
	}
	public List<Row> FindAll_PlotId(string find)
	{
		return rowList.FindAll(x => x.PlotId == find);
	}
	public Row Find_StudentID(string find)
	{
		return rowList.Find(x => x.StudentID == find);
	}
	public List<Row> FindAll_StudentID(string find)
	{
		return rowList.FindAll(x => x.StudentID == find);
	}
	public Row Find_SaveID(string find)
	{
		return rowList.Find(x => x.SaveID == find);
	}
	public List<Row> FindAll_SaveID(string find)
	{
		return rowList.FindAll(x => x.SaveID == find);
	}
	public Row Find_savePhoto(string find)
	{
		return rowList.Find(x => x.savePhoto == find);
	}
	public List<Row> FindAll_savePhoto(string find)
	{
		return rowList.FindAll(x => x.savePhoto == find);
	}
	public Row Find_Clothing(string find)
	{
		return rowList.Find(x => x.Clothing == find);
	}
	public List<Row> FindAll_Clothing(string find)
	{
		return rowList.FindAll(x => x.Clothing == find);
	}
	public Row Find_Face(string find)
	{
		return rowList.Find(x => x.Face == find);
	}
	public List<Row> FindAll_Face(string find)
	{
		return rowList.FindAll(x => x.Face == find);
	}
	public Row Find_心情(string find)
	{
		return rowList.Find(x => x.心情 == find);
	}
	public List<Row> FindAll_心情(string find)
	{
		return rowList.FindAll(x => x.心情 == find);
	}
	public Row Find_信任(string find)
	{
		return rowList.Find(x => x.信任 == find);
	}
	public List<Row> FindAll_信任(string find)
	{
		return rowList.FindAll(x => x.信任 == find);
	}
	public Row Find_气质(string find)
	{
		return rowList.Find(x => x.气质 == find);
	}
	public List<Row> FindAll_气质(string find)
	{
		return rowList.FindAll(x => x.气质 == find);
	}
	public Row Find_思维(string find)
	{
		return rowList.Find(x => x.思维 == find);
	}
	public List<Row> FindAll_思维(string find)
	{
		return rowList.FindAll(x => x.思维 == find);
	}
	public Row Find_口才(string find)
	{
		return rowList.Find(x => x.口才 == find);
	}
	public List<Row> FindAll_口才(string find)
	{
		return rowList.FindAll(x => x.口才 == find);
	}
	public Row Find_体质(string find)
	{
		return rowList.Find(x => x.体质 == find);
	}
	public List<Row> FindAll_体质(string find)
	{
		return rowList.FindAll(x => x.体质 == find);
	}
	public Row Find_善恶(string find)
	{
		return rowList.Find(x => x.善恶 == find);
	}
	public List<Row> FindAll_善恶(string find)
	{
		return rowList.FindAll(x => x.善恶 == find);
	}
	public Row Find_语文(string find)
	{
		return rowList.Find(x => x.语文 == find);
	}
	public List<Row> FindAll_语文(string find)
	{
		return rowList.FindAll(x => x.语文 == find);
	}
	public Row Find_数学(string find)
	{
		return rowList.Find(x => x.数学 == find);
	}
	public List<Row> FindAll_数学(string find)
	{
		return rowList.FindAll(x => x.数学 == find);
	}
	public Row Find_英语(string find)
	{
		return rowList.Find(x => x.英语 == find);
	}
	public List<Row> FindAll_英语(string find)
	{
		return rowList.FindAll(x => x.英语 == find);
	}
	public Row Find_政治(string find)
	{
		return rowList.Find(x => x.政治 == find);
	}
	public List<Row> FindAll_政治(string find)
	{
		return rowList.FindAll(x => x.政治 == find);
	}
	public Row Find_历史(string find)
	{
		return rowList.Find(x => x.历史 == find);
	}
	public List<Row> FindAll_历史(string find)
	{
		return rowList.FindAll(x => x.历史 == find);
	}
	public Row Find_地理(string find)
	{
		return rowList.Find(x => x.地理 == find);
	}
	public List<Row> FindAll_地理(string find)
	{
		return rowList.FindAll(x => x.地理 == find);
	}
	public Row Find_物理(string find)
	{
		return rowList.Find(x => x.物理 == find);
	}
	public List<Row> FindAll_物理(string find)
	{
		return rowList.FindAll(x => x.物理 == find);
	}
	public Row Find_化学(string find)
	{
		return rowList.Find(x => x.化学 == find);
	}
	public List<Row> FindAll_化学(string find)
	{
		return rowList.FindAll(x => x.化学 == find);
	}
	public Row Find_生物(string find)
	{
		return rowList.Find(x => x.生物 == find);
	}
	public List<Row> FindAll_生物(string find)
	{
		return rowList.FindAll(x => x.生物 == find);
	}
	public Row Find_音乐(string find)
	{
		return rowList.Find(x => x.音乐 == find);
	}
	public List<Row> FindAll_音乐(string find)
	{
		return rowList.FindAll(x => x.音乐 == find);
	}
	public Row Find_表演(string find)
	{
		return rowList.Find(x => x.表演 == find);
	}
	public List<Row> FindAll_表演(string find)
	{
		return rowList.FindAll(x => x.表演 == find);
	}
	public Row Find_舞蹈(string find)
	{
		return rowList.Find(x => x.舞蹈 == find);
	}
	public List<Row> FindAll_舞蹈(string find)
	{
		return rowList.FindAll(x => x.舞蹈 == find);
	}
	public Row Find_手工(string find)
	{
		return rowList.Find(x => x.手工 == find);
	}
	public List<Row> FindAll_手工(string find)
	{
		return rowList.FindAll(x => x.手工 == find);
	}
	public Row Find_棋技(string find)
	{
		return rowList.Find(x => x.棋技 == find);
	}
	public List<Row> FindAll_棋技(string find)
	{
		return rowList.FindAll(x => x.棋技 == find);
	}
	public Row Find_种植(string find)
	{
		return rowList.Find(x => x.种植 == find);
	}
	public List<Row> FindAll_种植(string find)
	{
		return rowList.FindAll(x => x.种植 == find);
	}
	public Row Find_摄影(string find)
	{
		return rowList.Find(x => x.摄影 == find);
	}
	public List<Row> FindAll_摄影(string find)
	{
		return rowList.FindAll(x => x.摄影 == find);
	}
	public Row Find_烹饪(string find)
	{
		return rowList.Find(x => x.烹饪 == find);
	}
	public List<Row> FindAll_烹饪(string find)
	{
		return rowList.FindAll(x => x.烹饪 == find);
	}
	public Row Find_考古(string find)
	{
		return rowList.Find(x => x.考古 == find);
	}
	public List<Row> FindAll_考古(string find)
	{
		return rowList.FindAll(x => x.考古 == find);
	}
	public Row Find_编程(string find)
	{
		return rowList.Find(x => x.编程 == find);
	}
	public List<Row> FindAll_编程(string find)
	{
		return rowList.FindAll(x => x.编程 == find);
	}
	public Row Find_绘画(string find)
	{
		return rowList.Find(x => x.绘画 == find);
	}
	public List<Row> FindAll_绘画(string find)
	{
		return rowList.FindAll(x => x.绘画 == find);
	}
	public Row Find_运动(string find)
	{
		return rowList.Find(x => x.运动 == find);
	}
	public List<Row> FindAll_运动(string find)
	{
		return rowList.FindAll(x => x.运动 == find);
	}
	public Row Find_TimeBucket(string find)
	{
		return rowList.Find(x => x.TimeBucket == find);
	}
	public List<Row> FindAll_TimeBucket(string find)
	{
		return rowList.FindAll(x => x.TimeBucket == find);
	}
	public Row Find_CourseID(string find)
	{
		return rowList.Find(x => x.CourseID == find);
	}
	public List<Row> FindAll_CourseID(string find)
	{
		return rowList.FindAll(x => x.CourseID == find);
	}
	public Row Find_LockTime(string find)
	{
		return rowList.Find(x => x.LockTime == find);
	}
	public List<Row> FindAll_LockTime(string find)
	{
		return rowList.FindAll(x => x.LockTime == find);
	}
	public Row Find_FriendID(string find)
	{
		return rowList.Find(x => x.FriendID == find);
	}
	public List<Row> FindAll_FriendID(string find)
	{
		return rowList.FindAll(x => x.FriendID == find);
	}
	public Row Find_FriendValue(string find)
	{
		return rowList.Find(x => x.FriendValue == find);
	}
	public List<Row> FindAll_FriendValue(string find)
	{
		return rowList.FindAll(x => x.FriendValue == find);
	}
	public Row Find_FriendMessage(string find)
	{
		return rowList.Find(x => x.FriendMessage == find);
	}
	public List<Row> FindAll_FriendMessage(string find)
	{
		return rowList.FindAll(x => x.FriendMessage == find);
	}

}