// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class TimerAndHintList
{
	public class Row
	{
		public string PlotId;
		public string RoleID;
		public string headline;
		public string text;
		public string isHint;
		public string isTimerShaftNode;
		public string saveID;

	}
	public TimerAndHintList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.PlotId = grid[i][0];
			row.RoleID = grid[i][1];
			row.headline = grid[i][2];
			row.text = grid[i][3];
			row.isHint = grid[i][4];
			row.isTimerShaftNode = grid[i][5];
			row.saveID = grid[i][6];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_PlotId(string find)
	{
		return rowList.Find(x => x.PlotId == find);
	}
	public List<Row> FindAll_PlotId(string find)
	{
		return rowList.FindAll(x => x.PlotId == find);
	}
	public Row Find_RoleID(string find)
	{
		return rowList.Find(x => x.RoleID == find);
	}
	public List<Row> FindAll_RoleID(string find)
	{
		return rowList.FindAll(x => x.RoleID == find);
	}
	public Row Find_headline(string find)
	{
		return rowList.Find(x => x.headline == find);
	}
	public List<Row> FindAll_headline(string find)
	{
		return rowList.FindAll(x => x.headline == find);
	}
	public Row Find_text(string find)
	{
		return rowList.Find(x => x.text == find);
	}
	public List<Row> FindAll_text(string find)
	{
		return rowList.FindAll(x => x.text == find);
	}
	public Row Find_isHint(string find)
	{
		return rowList.Find(x => x.isHint == find);
	}
	public List<Row> FindAll_isHint(string find)
	{
		return rowList.FindAll(x => x.isHint == find);
	}
	public Row Find_isTimerShaftNode(string find)
	{
		return rowList.Find(x => x.isTimerShaftNode == find);
	}
	public List<Row> FindAll_isTimerShaftNode(string find)
	{
		return rowList.FindAll(x => x.isTimerShaftNode == find);
	}
	public Row Find_saveID(string find)
	{
		return rowList.Find(x => x.saveID == find);
	}
	public List<Row> FindAll_saveID(string find)
	{
		return rowList.FindAll(x => x.saveID == find);
	}

}