// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class EnterHigherSchoolList
{
	public class Row
	{
		public string ID;
		public string TotalPoints;
		public string Student;
		public string SchoolName;
		public string Description;

	}
	public EnterHigherSchoolList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.ID = grid[i][0];
			row.TotalPoints = grid[i][1];
			row.Student = grid[i][2];
			row.SchoolName = grid[i][3];
			row.Description = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_ID(string find)
	{
		return rowList.Find(x => x.ID == find);
	}
	public List<Row> FindAll_ID(string find)
	{
		return rowList.FindAll(x => x.ID == find);
	}
	public Row Find_TotalPoints(string find)
	{
		return rowList.Find(x => x.TotalPoints == find);
	}
	public List<Row> FindAll_TotalPoints(string find)
	{
		return rowList.FindAll(x => x.TotalPoints == find);
	}
	public Row Find_Student(string find)
	{
		return rowList.Find(x => x.Student == find);
	}
	public List<Row> FindAll_Student(string find)
	{
		return rowList.FindAll(x => x.Student == find);
	}
	public Row Find_SchoolName(string find)
	{
		return rowList.Find(x => x.SchoolName == find);
	}
	public List<Row> FindAll_SchoolName(string find)
	{
		return rowList.FindAll(x => x.SchoolName == find);
	}
	public Row Find_Description(string find)
	{
		return rowList.Find(x => x.Description == find);
	}
	public List<Row> FindAll_Description(string find)
	{
		return rowList.FindAll(x => x.Description == find);
	}

}