// This code automatically generated by TableCodeGen

using System.Collections.Generic;
using Basic.CSV2Table.Scripts;
using UnityEngine;

namespace Basic.CSV2Table.GameOver
{
    public class EnterHigherSchoolList
    {
        public class Row
        {
            public string ID;
            public string TotalPoints;
            public string Student;
            public string SchoolName;
            public string Description;
        }

        public EnterHigherSchoolList(TextAsset csv)
        {
            Load(csv);
        }

        private List<Row> rowList = new();
        private bool isLoaded = false;

        public bool IsLoaded()
        {
            return isLoaded;
        }

        public List<Row> GetRowList()
        {
            return rowList;
        }

        public void Load(TextAsset csv)
        {
            rowList.Clear();
            var grid = CsvParser2.Parse(csv.text);
            for (var i = 1; i < grid.Length; i++)
            {
                var row = new Row();
                row.ID = grid[i][0];
                row.TotalPoints = grid[i][1];
                row.Student = grid[i][2];
                row.SchoolName = grid[i][3];
                row.Description = grid[i][4];

                rowList.Add(row);
            }

            isLoaded = true;
        }

        public int Count()
        {
            return rowList.Count;
        }

        public Row this[int i] => rowList[i];

        public Row Find_ID(string find)
        {
            return rowList.Find(x => x.ID == find);
        }

        public List<Row> FindAll_ID(string find)
        {
            return rowList.FindAll(x => x.ID == find);
        }

        public Row Find_TotalPoints(string find)
        {
            return rowList.Find(x => x.TotalPoints == find);
        }

        public List<Row> FindAll_TotalPoints(string find)
        {
            return rowList.FindAll(x => x.TotalPoints == find);
        }

        public Row Find_Student(string find)
        {
            return rowList.Find(x => x.Student == find);
        }

        public List<Row> FindAll_Student(string find)
        {
            return rowList.FindAll(x => x.Student == find);
        }

        public Row Find_SchoolName(string find)
        {
            return rowList.Find(x => x.SchoolName == find);
        }

        public List<Row> FindAll_SchoolName(string find)
        {
            return rowList.FindAll(x => x.SchoolName == find);
        }

        public Row Find_Description(string find)
        {
            return rowList.Find(x => x.Description == find);
        }

        public List<Row> FindAll_Description(string find)
        {
            return rowList.FindAll(x => x.Description == find);
        }
    }
}