// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class SchoolWorkList
{
	public class Row
	{
		public string TotalPoints;
		public string LeastValue;
		public string Description;

	}
	public SchoolWorkList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.TotalPoints = grid[i][0];
			row.LeastValue = grid[i][1];
			row.Description = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_TotalPoints(string find)
	{
		return rowList.Find(x => x.TotalPoints == find);
	}
	public List<Row> FindAll_TotalPoints(string find)
	{
		return rowList.FindAll(x => x.TotalPoints == find);
	}
	public Row Find_LeastValue(string find)
	{
		return rowList.Find(x => x.LeastValue == find);
	}
	public List<Row> FindAll_LeastValue(string find)
	{
		return rowList.FindAll(x => x.LeastValue == find);
	}
	public Row Find_Description(string find)
	{
		return rowList.Find(x => x.Description == find);
	}
	public List<Row> FindAll_Description(string find)
	{
		return rowList.FindAll(x => x.Description == find);
	}

}