// This code automatically generated by TableCodeGen

using System.Collections.Generic;
using Basic.CSV2Table.Scripts;
using UnityEngine;

namespace Basic.CSV2Table.GameOver
{
    public class SchoolWorkList
    {
        public class Row
        {
            public string TotalPoints;
            public string LeastValue;
            public string Description;
        }

        public SchoolWorkList(TextAsset csv)
        {
            Load(csv);
        }

        private List<Row> rowList = new();
        private bool isLoaded = false;

        public bool IsLoaded()
        {
            return isLoaded;
        }

        public List<Row> GetRowList()
        {
            return rowList;
        }

        public void Load(TextAsset csv)
        {
            rowList.Clear();
            var grid = CsvParser2.Parse(csv.text);
            for (var i = 1; i < grid.Length; i++)
            {
                var row = new Row();
                row.TotalPoints = grid[i][0];
                row.LeastValue = grid[i][1];
                row.Description = grid[i][2];

                rowList.Add(row);
            }

            isLoaded = true;
        }

        public int Count()
        {
            return rowList.Count;
        }

        public Row this[int i] => rowList[i];

        public Row Find_TotalPoints(string find)
        {
            return rowList.Find(x => x.TotalPoints == find);
        }

        public List<Row> FindAll_TotalPoints(string find)
        {
            return rowList.FindAll(x => x.TotalPoints == find);
        }

        public Row Find_LeastValue(string find)
        {
            return rowList.Find(x => x.LeastValue == find);
        }

        public List<Row> FindAll_LeastValue(string find)
        {
            return rowList.FindAll(x => x.LeastValue == find);
        }

        public Row Find_Description(string find)
        {
            return rowList.Find(x => x.Description == find);
        }

        public List<Row> FindAll_Description(string find)
        {
            return rowList.FindAll(x => x.Description == find);
        }
    }
}