// This code automatically generated by TableCodeGen

using System.Collections.Generic;
using Basic.CSV2Table.Scripts;
using UnityEngine;

namespace Basic.CSV2Table
{
    public class ArticleList
    {
        public class Row
        {
            public string ID;
            public string Name;
            public string Icon;
            public string description;
        }

        public ArticleList(TextAsset csv)
        {
            Load(csv);
        }

        private List<Row> rowList = new();
        private bool isLoaded = false;

        public bool IsLoaded()
        {
            return isLoaded;
        }

        public List<Row> GetRowList()
        {
            return rowList;
        }

        public void Load(TextAsset csv)
        {
            rowList.Clear();
            var grid = CsvParser2.Parse(csv.text);
            for (var i = 1; i < grid.Length; i++)
            {
                var row = new Row();
                row.ID = grid[i][0];
                row.Name = grid[i][1];
                row.Icon = grid[i][2];
                row.description = grid[i][3];

                rowList.Add(row);
            }

            isLoaded = true;
        }

        public int Count()
        {
            return rowList.Count;
        }

        public Row this[int i] => rowList[i];

        public Row Find_ID(string find)
        {
            return rowList.Find(x => x.ID == find);
        }

        public List<Row> FindAll_ID(string find)
        {
            return rowList.FindAll(x => x.ID == find);
        }

        public Row Find_Name(string find)
        {
            return rowList.Find(x => x.Name == find);
        }

        public List<Row> FindAll_Name(string find)
        {
            return rowList.FindAll(x => x.Name == find);
        }

        public Row Find_Icon(string find)
        {
            return rowList.Find(x => x.Icon == find);
        }

        public List<Row> FindAll_Icon(string find)
        {
            return rowList.FindAll(x => x.Icon == find);
        }

        public Row Find_description(string find)
        {
            return rowList.Find(x => x.description == find);
        }

        public List<Row> FindAll_description(string find)
        {
            return rowList.FindAll(x => x.description == find);
        }
    }
}