// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class DailyNews
{
	public class Row
	{
		public string id;
		public string year;
		public string text;

	}
	public DailyNews(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.year = grid[i][1];
			row.text = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_year(string find)
	{
		return rowList.Find(x => x.year == find);
	}
	public List<Row> FindAll_year(string find)
	{
		return rowList.FindAll(x => x.year == find);
	}
	public Row Find_text(string find)
	{
		return rowList.Find(x => x.text == find);
	}
	public List<Row> FindAll_text(string find)
	{
		return rowList.FindAll(x => x.text == find);
	}

}