// This code automatically generated by TableCodeGen

using System.Collections.Generic;
using Basic.CSV2Table.Scripts;
using UnityEngine;

namespace Basic.CSV2Table
{
    public class DailyNews
    {
        public class Row
        {
            public string id;
            public string year;
            public string text;
        }

        public DailyNews(TextAsset csv)
        {
            Load(csv);
        }

        private List<Row> rowList = new();
        private bool isLoaded = false;

        public bool IsLoaded()
        {
            return isLoaded;
        }

        public List<Row> GetRowList()
        {
            return rowList;
        }

        public void Load(TextAsset csv)
        {
            rowList.Clear();
            var grid = CsvParser2.Parse(csv.text);
            for (var i = 1; i < grid.Length; i++)
            {
                var row = new Row();
                row.id = grid[i][0];
                row.year = grid[i][1];
                row.text = grid[i][2];

                rowList.Add(row);
            }

            isLoaded = true;
        }

        public int Count()
        {
            return rowList.Count;
        }

        public Row this[int i] => rowList[i];

        public Row Find_id(string find)
        {
            return rowList.Find(x => x.id == find);
        }

        public List<Row> FindAll_id(string find)
        {
            return rowList.FindAll(x => x.id == find);
        }

        public Row Find_year(string find)
        {
            return rowList.Find(x => x.year == find);
        }

        public List<Row> FindAll_year(string find)
        {
            return rowList.FindAll(x => x.year == find);
        }

        public Row Find_text(string find)
        {
            return rowList.Find(x => x.text == find);
        }

        public List<Row> FindAll_text(string find)
        {
            return rowList.FindAll(x => x.text == find);
        }
    }
}