// This code automatically generated by TableCodeGen

using System.Collections.Generic;
using Basic.CSV2Table.Scripts;
using UnityEngine;

namespace Basic.CSV2Table
{
    public class NpcList
    {
        public class Row
        {
            public string id;
            public string name;
            public string gender;
            public string description;
        }

        public NpcList(TextAsset csv)
        {
            Load(csv);
        }

        private List<Row> rowList = new();
        private bool isLoaded = false;

        public bool IsLoaded()
        {
            return isLoaded;
        }

        public List<Row> GetRowList()
        {
            return rowList;
        }

        public void Load(TextAsset csv)
        {
            rowList.Clear();
            var grid = CsvParser2.Parse(csv.text);
            for (var i = 1; i < grid.Length; i++)
            {
                var row = new Row();
                row.id = grid[i][0];
                row.name = grid[i][1];
                row.gender = grid[i][2];
                row.description = grid[i][3];

                rowList.Add(row);
            }

            isLoaded = true;
        }

        public int Count()
        {
            return rowList.Count;
        }

        public Row this[int i] => rowList[i];

        public Row Find_id(string find)
        {
            return rowList.Find(x => x.id == find);
        }

        public List<Row> FindAll_id(string find)
        {
            return rowList.FindAll(x => x.id == find);
        }

        public Row Find_name(string find)
        {
            return rowList.Find(x => x.name == find);
        }

        public List<Row> FindAll_name(string find)
        {
            return rowList.FindAll(x => x.name == find);
        }

        public Row Find_gender(string find)
        {
            return rowList.Find(x => x.gender == find);
        }

        public List<Row> FindAll_gender(string find)
        {
            return rowList.FindAll(x => x.gender == find);
        }

        public Row Find_description(string find)
        {
            return rowList.Find(x => x.description == find);
        }

        public List<Row> FindAll_description(string find)
        {
            return rowList.FindAll(x => x.description == find);
        }
    }
}