// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class PlayerCourseList
{
	public class Row
	{
		public string Id;
		public string Name;
		public string description;
		public string courseId;
		public string classroom;

	}
	public PlayerCourseList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.Id = grid[i][0];
			row.Name = grid[i][1];
			row.description = grid[i][2];
			row.courseId = grid[i][3];
			row.classroom = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_Id(string find)
	{
		return rowList.Find(x => x.Id == find);
	}
	public List<Row> FindAll_Id(string find)
	{
		return rowList.FindAll(x => x.Id == find);
	}
	public Row Find_Name(string find)
	{
		return rowList.Find(x => x.Name == find);
	}
	public List<Row> FindAll_Name(string find)
	{
		return rowList.FindAll(x => x.Name == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_courseId(string find)
	{
		return rowList.Find(x => x.courseId == find);
	}
	public List<Row> FindAll_courseId(string find)
	{
		return rowList.FindAll(x => x.courseId == find);
	}
	public Row Find_classroom(string find)
	{
		return rowList.Find(x => x.classroom == find);
	}
	public List<Row> FindAll_classroom(string find)
	{
		return rowList.FindAll(x => x.classroom == find);
	}

}