// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class StudentMarkList
{
	public class Row
	{
		public string Year;
		public string semester;
		public string Type;
		public string Total;
		public string Content;

	}
	public StudentMarkList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.Year = grid[i][0];
			row.semester = grid[i][1];
			row.Type = grid[i][2];
			row.Total = grid[i][3];
			row.Content = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_Year(string find)
	{
		return rowList.Find(x => x.Year == find);
	}
	public List<Row> FindAll_Year(string find)
	{
		return rowList.FindAll(x => x.Year == find);
	}
	public Row Find_semester(string find)
	{
		return rowList.Find(x => x.semester == find);
	}
	public List<Row> FindAll_semester(string find)
	{
		return rowList.FindAll(x => x.semester == find);
	}
	public Row Find_Type(string find)
	{
		return rowList.Find(x => x.Type == find);
	}
	public List<Row> FindAll_Type(string find)
	{
		return rowList.FindAll(x => x.Type == find);
	}
	public Row Find_Total(string find)
	{
		return rowList.Find(x => x.Total == find);
	}
	public List<Row> FindAll_Total(string find)
	{
		return rowList.FindAll(x => x.Total == find);
	}
	public Row Find_Content(string find)
	{
		return rowList.Find(x => x.Content == find);
	}
	public List<Row> FindAll_Content(string find)
	{
		return rowList.FindAll(x => x.Content == find);
	}

}