// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class StoreGoodsList
{
	public class Row
	{
		public string name;
		public string courseID;
		public string description;
		public string courseDescriptiondescription;
		public string price;
		public string manufacturerName;

	}
	public StoreGoodsList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.name = grid[i][0];
			row.courseID = grid[i][1];
			row.description = grid[i][2];
			row.courseDescriptiondescription = grid[i][3];
			row.price = grid[i][4];
			row.manufacturerName = grid[i][5];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_courseID(string find)
	{
		return rowList.Find(x => x.courseID == find);
	}
	public List<Row> FindAll_courseID(string find)
	{
		return rowList.FindAll(x => x.courseID == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_courseDescriptiondescription(string find)
	{
		return rowList.Find(x => x.courseDescriptiondescription == find);
	}
	public List<Row> FindAll_courseDescriptiondescription(string find)
	{
		return rowList.FindAll(x => x.courseDescriptiondescription == find);
	}
	public Row Find_price(string find)
	{
		return rowList.Find(x => x.price == find);
	}
	public List<Row> FindAll_price(string find)
	{
		return rowList.FindAll(x => x.price == find);
	}
	public Row Find_manufacturerName(string find)
	{
		return rowList.Find(x => x.manufacturerName == find);
	}
	public List<Row> FindAll_manufacturerName(string find)
	{
		return rowList.FindAll(x => x.manufacturerName == find);
	}

}