// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections.Generic;

public class SupermarketGoodsList
{
	public class Row
	{
		public string id;
		public string minQuantity;
		public string maxQuantity;
		public string price;
		public string productionCompany;
		public string state;
		public string SaleProbability;

	}
	public SupermarketGoodsList(TextAsset csv)
	{
		Load(csv);
	}
	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded() => isLoaded;

	public List<Row> GetRowList() => rowList;

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.minQuantity = grid[i][1];
			row.maxQuantity = grid[i][2];
			row.price = grid[i][3];
			row.productionCompany = grid[i][4];
			row.state = grid[i][5];
			row.SaleProbability = grid[i][6];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int Count() => rowList.Count;
	public Row this[int i] => rowList[i];

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_minQuantity(string find)
	{
		return rowList.Find(x => x.minQuantity == find);
	}
	public List<Row> FindAll_minQuantity(string find)
	{
		return rowList.FindAll(x => x.minQuantity == find);
	}
	public Row Find_maxQuantity(string find)
	{
		return rowList.Find(x => x.maxQuantity == find);
	}
	public List<Row> FindAll_maxQuantity(string find)
	{
		return rowList.FindAll(x => x.maxQuantity == find);
	}
	public Row Find_price(string find)
	{
		return rowList.Find(x => x.price == find);
	}
	public List<Row> FindAll_price(string find)
	{
		return rowList.FindAll(x => x.price == find);
	}
	public Row Find_productionCompany(string find)
	{
		return rowList.Find(x => x.productionCompany == find);
	}
	public List<Row> FindAll_productionCompany(string find)
	{
		return rowList.FindAll(x => x.productionCompany == find);
	}
	public Row Find_state(string find)
	{
		return rowList.Find(x => x.state == find);
	}
	public List<Row> FindAll_state(string find)
	{
		return rowList.FindAll(x => x.state == find);
	}
	public Row Find_SaleProbability(string find)
	{
		return rowList.Find(x => x.SaleProbability == find);
	}
	public List<Row> FindAll_SaleProbability(string find)
	{
		return rowList.FindAll(x => x.SaleProbability == find);
	}

}